# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d4d90ba0819f1ad94c7f3a42f8cd5eb7ef395134def2f8d4b27994995bd128eb649d7aed1ea9c7a0257151b723da6cd39341dd23f1d478b4a5a5c5baf7e2625

test:
  secret_key_base: 96e5779db4b2ee2424e44b1d8f6015bdbfe4f33bed10e8ed5c8e2f667621a2c2fa3bf1cbcb0f14da39fc69cf82e9618b63c31c34a5b268959517bd4c019a1e25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
